eventos_pipeline:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: dataleaguenovaretail
      dataset: nR
      threads: 4
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"
      location: us-south1
      priority: interactive
      retries: 1
